/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1_richardson_lainez;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RALC
 */
public class Principal extends javax.swing.JFrame {
static int ban;
static Familiares administrador;
static boolean admin;
static boolean familiar;
static int cant_padre=0;
static int cant_hermana=0;
static int cant_hermano=0;
static int cant_esposo=0;
static ArrayList <Personas> personas = new ArrayList();
static ArrayList <Familiares> familiares = new ArrayList();
static ArrayList <Personal> personal = new ArrayList();
static ArrayList <Objetos> objetos = new ArrayList();
static ArrayList <Zapatos> zapatos = new ArrayList();
static ArrayList <Ropa> ropa = new ArrayList();
static ArrayList <Objetos_hogar> objetos_hogar = new ArrayList();

    /**
     * Creates new form Principal
     */
    public Principal() {
        administrador = new Familiares();
        admin = false;
        familiar = false;
        crearAdministrados();
        initComponents();
        
        
       
    }
    public static void crearAdministrados(){
        administrador.setNombre("Kym Kandashian");
        administrador.setRol("Madre");
        administrador.setContrasena("contra");
        administrador.setUsuario("user");
        
               personas.add(administrador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Registrar = new javax.swing.JPanel();
        tf_edad = new javax.swing.JTextField();
        bt_registrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rb_m = new javax.swing.JRadioButton();
        rb_f = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        tf_estado_civil = new javax.swing.JTextField();
        cb_tipo_persona = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_rol = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        tf_trabajo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_altura = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_peso = new javax.swing.JTextField();
        tf_ocupacion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_horarios = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_tiempo_trabajando = new javax.swing.JTextField();
        tf_usuario_r = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        tf_contra_r = new javax.swing.JTextField();
        AnadirObjetos = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tf_descripcion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tf_marca = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tf_tamano = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tf_precio = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        bt_color = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        cb_dueno = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        cb_tipo_objetos = new javax.swing.JComboBox<>();
        tf_talla_zapatos = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tf_tipo_suela = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        cb_confort = new javax.swing.JComboBox<>();
        tf_talla_ropa = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tf_material = new javax.swing.JTextField();
        tf_tiempo_vida = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        tf_intrucciones = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jd_fecha = new com.toedter.calendar.JDateChooser();
        jL_elaborado_pais = new com.toedter.components.JLocaleChooser();
        jb_crear_objetos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cb_mensaje_personas = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        tf_mensaje_enviar = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jb_enviar_mensaje = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        cb_mensajes_recibidos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        cb_modificar = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        Ingreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_contrasena = new javax.swing.JTextField();
        bt_ingresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(51, 0, 255));
        jTabbedPane1.setForeground(new java.awt.Color(102, 102, 255));

        Registrar.setBackground(new java.awt.Color(153, 153, 255));

        bt_registrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_registrar.setText("Registrar");
        bt_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Edad");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Sexo");

        rb_m.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_m.setText("M");

        rb_f.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_f.setText("F");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Estado Civil");

        cb_tipo_persona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Familiares", "Personal" }));
        cb_tipo_persona.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipo_personaItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Tipo Persona");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Rol");

        cb_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Padre", "Hermana", "Hermano", "Esposo" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Trabajo");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Altura");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Peso");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Ocupación dentro de la casa");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Horarios de Trabajo");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Tiempo que lleva trabajando");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("Usuario");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("Contraseña");

        javax.swing.GroupLayout RegistrarLayout = new javax.swing.GroupLayout(Registrar);
        Registrar.setLayout(RegistrarLayout);
        RegistrarLayout.setHorizontalGroup(
            RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrarLayout.createSequentialGroup()
                        .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_usuario_r, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38)
                            .addComponent(tf_contra_r, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegistrarLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistrarLayout.createSequentialGroup()
                                .addComponent(rb_m)
                                .addGap(18, 18, 18)
                                .addComponent(rb_f)))
                        .addContainerGap())
                    .addGroup(RegistrarLayout.createSequentialGroup()
                        .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(tf_estado_civil, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrarLayout.createSequentialGroup()
                                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(RegistrarLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(28, 28, 28)
                                        .addComponent(cb_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(RegistrarLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(28, 28, 28)
                                        .addComponent(cb_tipo_persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(112, 112, 112))
                            .addGroup(RegistrarLayout.createSequentialGroup()
                                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(RegistrarLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(RegistrarLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(RegistrarLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(RegistrarLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(RegistrarLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_horarios, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(RegistrarLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_tiempo_trabajando, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(102, 102, 102))))))
            .addGroup(RegistrarLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(bt_registrar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        RegistrarLayout.setVerticalGroup(
            RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrarLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_tipo_persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistrarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tf_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistrarLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tf_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_m)
                            .addComponent(rb_f)))
                    .addGroup(RegistrarLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addGap(2, 2, 2)
                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_estado_civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tf_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel14)
                    .addComponent(tf_horarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_usuario_r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel38)
                    .addGroup(RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(tf_tiempo_trabajando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_contra_r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_registrar)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar", Registrar);

        AnadirObjetos.setBackground(new java.awt.Color(255, 51, 102));
        AnadirObjetos.setForeground(new java.awt.Color(51, 0, 204));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Descripcion");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Marca");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Tamaño");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Calidad");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Precio");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Dueño");

        bt_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_colorMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Color");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Tipo");

        cb_tipo_objetos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zapatos", "Ropa", "Objetos_hogar" }));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Talla");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Tipo de suela");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Confort");

        cb_confort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Talla");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Material");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Elaboracion Pais");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Tiempo de Vida");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Area de casa");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cocina", "Sala", "Habitación" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Instrucciones de Aramado");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Fecha de Compra");

        jb_crear_objetos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jb_crear_objetos.setText("Crear Objetos");
        jb_crear_objetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crear_objetosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AnadirObjetosLayout = new javax.swing.GroupLayout(AnadirObjetos);
        AnadirObjetos.setLayout(AnadirObjetosLayout);
        AnadirObjetosLayout.setHorizontalGroup(
            AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnadirObjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(38, 38, 38)
                        .addComponent(cb_dueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AnadirObjetosLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_talla_zapatos, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AnadirObjetosLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(38, 38, 38)
                                .addComponent(cb_tipo_objetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jb_crear_objetos)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnadirObjetosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnadirObjetosLayout.createSequentialGroup()
                                    .addComponent(jLabel33)
                                    .addGap(231, 231, 231))
                                .addGroup(AnadirObjetosLayout.createSequentialGroup()
                                    .addGap(95, 95, 95)
                                    .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(AnadirObjetosLayout.createSequentialGroup()
                                            .addComponent(jLabel26)
                                            .addGap(18, 18, 18)
                                            .addComponent(cb_confort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(AnadirObjetosLayout.createSequentialGroup()
                                            .addComponent(jLabel25)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tf_tipo_suela, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(AnadirObjetosLayout.createSequentialGroup()
                                            .addComponent(jLabel27)
                                            .addGap(41, 41, 41)
                                            .addComponent(tf_talla_ropa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(AnadirObjetosLayout.createSequentialGroup()
                                            .addComponent(jLabel28)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tf_material, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(35, 35, 35)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnadirObjetosLayout.createSequentialGroup()
                                .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_tiempo_vida, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jL_elaborado_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnadirObjetosLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(76, 76, 76)
                                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnadirObjetosLayout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jd_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_intrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );
        AnadirObjetosLayout.setVerticalGroup(
            AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnadirObjetosLayout.createSequentialGroup()
                .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_crear_objetos)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AnadirObjetosLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(tf_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AnadirObjetosLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tf_talla_ropa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel27))
                                    .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(tf_tipo_suela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AnadirObjetosLayout.createSequentialGroup()
                                .addComponent(cb_confort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addComponent(jLabel26))))
                .addGap(22, 22, 22)
                .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                        .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(tf_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(cb_dueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                        .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(tf_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jL_elaborado_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(tf_tiempo_vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)))
                .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(cb_tipo_objetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(tf_talla_zapatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addGap(30, 30, 30)
                        .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(tf_intrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(AnadirObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel33)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AnadirObjetosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jd_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(200, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Añadir Objetos", AnadirObjetos);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        cb_mensaje_personas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_mensaje_personasItemStateChanged(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("Persona");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Mensaje:");

        jb_enviar_mensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jb_enviar_mensaje.setText("Enviar");
        jb_enviar_mensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_enviar_mensajeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel34)
                        .addGap(55, 55, 55)
                        .addComponent(cb_mensaje_personas, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(tf_mensaje_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jb_enviar_mensaje)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_mensaje_personas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(90, 90, 90)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_mensaje_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jb_enviar_mensaje)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Enviar Mensaje", jPanel1);

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Persona:");

        cb_mensajes_recibidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_mensajes_recibidosItemStateChanged(evt);
            }
        });

        tabla1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Mensajes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel36)
                .addGap(97, 97, 97)
                .addComponent(cb_mensajes_recibidos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(cb_mensajes_recibidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(449, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mensajes Recibidos", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        cb_modificar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_modificarItemStateChanged(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setText("Personas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel39)
                .addGap(44, 44, 44)
                .addComponent(cb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addContainerGap(616, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar", jPanel3);

        Ingreso.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña");

        bt_ingresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_ingresar.setText("Ingresar");

        javax.swing.GroupLayout IngresoLayout = new javax.swing.GroupLayout(Ingreso);
        Ingreso.setLayout(IngresoLayout);
        IngresoLayout.setHorizontalGroup(
            IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresoLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(tf_usuario)
                        .addComponent(tf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IngresoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(bt_ingresar)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        IngresoLayout.setVerticalGroup(
            IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresoLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(bt_ingresar)
                .addContainerGap(342, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ingreso", Ingreso);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarMouseClicked
        // TODO add your handling code here:
        String nombre="";
         int edad=0;
         String id="";
        String sexo="";
        String estado_civil="";
        String usuario="";
        String contrasena="";//personas qui
        
        String rol="";
        String trabajo="";
        int altura=0;
        int peso=0;//familiaresaqio
        
        String ocupacion="";
        String horario_trabajo="";
        double tiempo_trabajando=0;//semanas
        double suelto=0;
        
        DefaultComboBoxModel modelo =
                        (DefaultComboBoxModel) cb_mensaje_personas.getModel();
                //modelo.addElement(x);//así lo inseetmoas directamente a la vista
              //  cb_mensaje_personas.setModel(modelo);//esto algunas veces lo podemos omitir, solo que alguans versiones de java no lo hacen
        
        try {
            nombre = tf_nombre.getText();
            edad = Integer.parseInt(tf_edad.getText());
            id = tf_id.getText();
            if (rb_m.isSelected()) {
                    sexo = "M";
                }else{
                    sexo = "F";
            }
            estado_civil = tf_estado_civil.getText();
            usuario = tf_usuario_r.getText();
            contrasena = tf_contra_r.getText();
            
            String temp = cb_tipo_persona.getSelectedItem().getClass().getName();
            int verf = 0;
            if (temp.equals("Familiares")) {
                String temp1 =cb_rol.getSelectedItem().getClass().getName();
                switch (temp1) {
                    case "Padre":
                        if(cant_padre < 1){
                            cant_padre++;
                            rol = "Padre";
                        }else{
                            verf = 1;
                            break;
                        }
                        break;
                    case "Hermana":
                        if(cant_hermana < 5){
                            cant_hermana++;
                            rol = "Hermana";
                        }else{
                            verf = 1;
                            break;
                        }
                        break;
                    case "Hermano":
                        if(cant_hermano < 1){
                            cant_hermano++;
                            rol = "Hermano";
                        }else{
                            verf = 1;
                            break;
                        }
                        break;
                    case "Esposo":
                        if(cant_esposo < 1){
                            cant_esposo++;
                            rol = "Esposo";
                        }else{
                            verf = 1;
                            break;
                        }
                        break;
                }
                if (verf ==0) {
                    trabajo = tf_trabajo.getText();
                   altura = Integer.parseInt(tf_altura.getText());
                   peso = Integer.parseInt(tf_peso.getText());
                   personas.add(new Familiares(rol, trabajo, altura, peso, nombre, edad, id, sexo, estado_civil));
                   familiares.add(new Familiares(rol, trabajo, altura, peso, nombre, edad, id, sexo, estado_civil));
                   modelo.addElement(new Familiares(rol, trabajo, altura, peso, nombre, edad, id, sexo, estado_civil));
                }else{
                    JOptionPane.showMessageDialog(null, "Lo siento, el rol que elegiste ya está lleno");
                    verf = 0;
                }
            }else{
                ocupacion = tf_ocupacion.getText();
                horario_trabajo = tf_horarios.getText();
                tiempo_trabajando = Double.parseDouble(tf_trabajo.getText());
                //suelto = Double.parseDouble(tf_)
                personas.add(new Personal(ocupacion, horario_trabajo, tiempo_trabajando, suelto, nombre, edad, id, sexo, estado_civil));
                personal.add(new Personal(ocupacion, horario_trabajo, tiempo_trabajando, suelto, nombre, edad, id, sexo, estado_civil));
                modelo.addElement(new Personal(ocupacion, horario_trabajo, tiempo_trabajando, suelto, nombre, edad, id, sexo, estado_civil));
            }
            cb_mensaje_personas.setModel(modelo);
            cb_dueno.setModel(modelo);
            cb_mensajes_recibidos.setModel(modelo);
            cb_modificar.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "¡Ocurrio un error, no se guardaron los datos");
        }
        
        
    }//GEN-LAST:event_bt_registrarMouseClicked

    private void jb_crear_objetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crear_objetosMouseClicked
        // TODO add your handling code here:
        Color color = Color.black;
        String descripcion="";
        String marca="";
        int tamano=0;
        int calidad=0;
        double precio=0;
        Personas dueño;//objetos
        
        String talla="";//zapatos
        String tipo_suela="";
        int confort=0; //1-10
        
        String talla2="";//ropa
        String material="";
        String pais_elaboracion="";
        
        String tiempo_vida="";//objetos_hogar
        String area_casa="";
        String instrucciones_armado="";
        String fecha_compra="";
        
        try {
            color =  bt_color.getBackground();
            descripcion = tf_descripcion.getText();
            marca = tf_marca.getText();
            tamano = Integer.parseInt(tf_tamano.getText());
            calidad = jComboBox3.getSelectedIndex()+1;
            precio = Double.parseDouble(tf_precio.getText());
            dueño = (Personas)cb_dueno.getSelectedItem();
            if (cb_tipo_objetos.getSelectedIndex() == 0) {
                talla = tf_talla_zapatos.getText();
                material = tf_material.getText();
                //pais_elaboracion = jL_elaborado_pais.getName();
                objetos.add(new Zapatos(talla, tipo_suela, confort, color, descripcion, marca, tamano, calidad, precio, dueño));
                zapatos.add(new Zapatos(talla, tipo_suela, confort, color, descripcion, marca, tamano, calidad, precio, dueño));
            }else if(cb_tipo_objetos.getSelectedIndex() == 1){
                //ropa
                talla2 = tf_talla_ropa.getText();
                material = tf_material.getText();
                pais_elaboracion = jL_elaborado_pais.getName();
                objetos.add(new Ropa(talla, material, pais_elaboracion, color, descripcion, marca, tamano, calidad, precio, dueño));
                ropa.add(new Ropa(talla, material, pais_elaboracion, color, descripcion, marca, tamano, calidad, precio, dueño));
            }else{
                //objetoshogar
                tiempo_vida = tf_tiempo_vida.getText();
                area_casa = jComboBox7.getName();
                instrucciones_armado = tf_intrucciones.getText();
                fecha_compra = jd_fecha.getDate()+"";
                objetos.add(new Objetos_hogar(tiempo_vida, area_casa, instrucciones_armado, fecha_compra, color, descripcion, marca, tamano, calidad, precio, dueño));
                objetos_hogar.add(new Objetos_hogar(tiempo_vida, area_casa, instrucciones_armado, fecha_compra, color, descripcion, marca, tamano, calidad, precio, dueño));
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lo sentimos, pero los datos no se guardaron");
        }
        
        
        
        
        
    }//GEN-LAST:event_jb_crear_objetosMouseClicked

    private void bt_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_colorMouseClicked
        // TODO add your handling code here:
        bt_color.setBackground(
                JColorChooser.showDialog(this, "Selecciones un color", Color.yellow));
        
        
    }//GEN-LAST:event_bt_colorMouseClicked

    private void cb_mensaje_personasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_mensaje_personasItemStateChanged
        // TODO add your handling code here:
        DefaultComboBoxModel modelo =
                        (DefaultComboBoxModel) cb_mensaje_personas.getModel();
                //modelo.addElement(x);//así lo inseetmoas directamente a la vista
                cb_mensaje_personas.setModel(modelo);//esto algunas veces lo podemos omitir, solo que alguans versiones de java no lo hacen
        
        
        
    }//GEN-LAST:event_cb_mensaje_personasItemStateChanged

    private void jb_enviar_mensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_enviar_mensajeMouseClicked
        // TODO add your handling code here:
        Personas p = (Personas) cb_mensaje_personas.getSelectedItem();
        String mensaje = tf_mensaje_enviar.getText()+"";
        mensaje = cifrado_cesar("cifrar", mensaje);
        mensaje = cifrado_trasposicion(mensaje);
        p.getMensajes().add(mensaje);
        JOptionPane.showMessageDialog(null, "Su mensaje fue enviado con éxito");
    }//GEN-LAST:event_jb_enviar_mensajeMouseClicked

    private void cb_mensajes_recibidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_mensajes_recibidosItemStateChanged
        // TODO add your handling code here:
                //esta validacion es para que no me agregue dos veces la misma cosa
                //porque este expande y colapsa, con esta validacion  solo xolpsa creo
                String s = ((Personas)cb_mensajes_recibidos.getSelectedItem()).getMensajes().get(0).toString();
                s = descifrado_trasposicion(s);
                s = cifrado_cesar("descifrar", s);
                Object [] newrow = {
                    s
                };
                DefaultTableModel modelo =
                        (DefaultTableModel) tabla1.getModel();
                modelo.addRow(newrow);
                tabla1.setModel(modelo);
            
        
        
        
    }//GEN-LAST:event_cb_mensajes_recibidosItemStateChanged

    private void cb_modificarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_modificarItemStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cb_modificarItemStateChanged

    private void cb_tipo_personaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipo_personaItemStateChanged
        // TODO add your handling code here:
        boolean mostrar;
        if (cb_tipo_objetos.getSelectedIndex() == 0) {
            tf_trabajo.setVisible(true);
            tf_altura.setVisible(true);
            tf_peso.setVisible(true);
            jLabel12.setVisible(true);
            jLabel11.setVisible(true);
            jLabel10.setVisible(true);
            jLabel9.setVisible(true);
            cb_rol.setVisible(true);
            
            jLabel13.setVisible(false);
            jLabel14.setVisible(false);
            jLabel15.setVisible(false);
            tf_ocupacion.setVisible(false);
            tf_horarios.setVisible(false);
            tf_tiempo_trabajando.setVisible(false);
        }else{
            tf_trabajo.setVisible(false);
            tf_altura.setVisible(false);
            tf_peso.setVisible(false);
            jLabel12.setVisible(false);
            jLabel11.setVisible(false);
            jLabel10.setVisible(false);
            jLabel9.setVisible(false);
            cb_rol.setVisible(false);
            
            jLabel13.setVisible(true);
            jLabel14.setVisible(true);
            jLabel15.setVisible(true);
            tf_ocupacion.setVisible(true);
            tf_horarios.setVisible(true);
            tf_tiempo_trabajando.setVisible(true);
        }
    }//GEN-LAST:event_cb_tipo_personaItemStateChanged

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
                
            }
        });
    }
    
    
    
    public static String cifrado_cesar(String operacion, String cadena){
        String cadenaCifrada = "";
        for (int i = 0; i < cadena.length(); i++) {
            char caracter = cadena.toLowerCase().charAt(i);
            if(caracter>=97 && caracter<=122){
                if(operacion.equals("cifrar")){
                    if(caracter>='x'){
                        caracter = (char)('a' + ('z'-caracter));
                    }else{
                        caracter+=3;
                    }
                    cadenaCifrada+=(char)(caracter);
                }else{
                    if(caracter<='c'){
                        caracter = (char)('z' - (caracter -'a'));
                    }else{
                        caracter-=3;
                    }
                    cadenaCifrada+=(char)(caracter);
                }
            }else{
                cadenaCifrada+=caracter;
            }
        }
 
        cadena = cadenaCifrada;
        return cadena;
    }
    
    public static String cifrado_trasposicion(String x){
        String cadenaCifrada = "";
        x = x.toLowerCase();
        /*ArrayList temp = new ArrayList();
        for (int i = 0; i < x.length(); i++) {
            if (x.charAt(i)== ' ') {
                temp.add('ó');
            }else{
                temp.add(x.charAt(i));
            }
        }
        int col = (temp.size()/5);
        int pos_ac = 0;
        for (int i = 0; i < col; i++) {
            int pos_sen = pos_ac;
            for (int j = pos_sen; j < pos_sen+5; j++) {
                cadenaCifrada += temp.get(pos_ac);
                pos_ac++;
            }
        }*/
        int col = (x.length()/3)+1; //esto me dará el número de columnas
        ban = col;
        char [][] matriz = new char [col][col];
        int cont = 0;
        for (int i = 0; i < col; i++) {
            for (int c = 0; c < col; c++) {
                if (cont >= x.length()) {
                    matriz[i][c] = 'á';
                }else{
                    if (x.charAt(cont)== ' ') {
                        matriz[i][c] = 'é';
                    }else{
                        matriz[i][c] = x.charAt(cont);
                        cont++;
                    }
                }
            }
        }
        for (int i = 0; i < col; i++) {
            for (int j = 0; j < col; j++) {
                cadenaCifrada += matriz[j][i];
            }
            cadenaCifrada += " ";
        }
        return cadenaCifrada;
    }
    
    public static String descifrado_trasposicion(String x){
        String descadenaCifrada = "";
        x = x.toLowerCase();
        int cont = 0;
        char[][] matriz = new char [ban][ban]; 
        x= x.replaceAll(" ", "");
        for (int i = 0; i < ban; i++) {
            for (int j = 0; j < ban; j++) {
                //matriz[j][i] = x.charAt(cont);
                //cont++;
                if (x.charAt(cont) == 'é') {
                    matriz[j][i] = ' ';
                }else{
                    matriz[j][i] = x.charAt(cont);
                }                
            }
        }
        for (int i = 0; i < ban; i++) {
            for (int j = 0; j < ban; j++) {
                if (matriz[i][j]!='á') {
                    descadenaCifrada += matriz[i][j];
                }
            }
        }
        return descadenaCifrada;
    }
    
    public static void login(){
        int x = 0;
        do{
            String user = JOptionPane.showInputDialog("Usuario:");
            String contra = JOptionPane.showInputDialog("Contra:");
            if(user == "user" && contra == "contra"){
                admin = true;
                JOptionPane.showMessageDialog(null, "Saludos, administradora");
                x=1;
            }else{
                admin = false;
                for (Personas t : personas) {
                    if ((t.getUsuario() == user) && (t.getContrasena() == contra)) {
                        JOptionPane.showMessageDialog(null, "Bienvenido usuario");
                         x = 1;
                        break;  
                    }else{
                        x=0;
                        JOptionPane.showMessageDialog(null, "Contrasena o usuario incorrctos\n"
                                + "Para continuar deberá ingresar bien la password y el usuario");
                    }
                }
            }
        }while(x !=0);
    }
    public static void registrar(){
         
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AnadirObjetos;
    private javax.swing.JPanel Ingreso;
    private javax.swing.JPanel Registrar;
    private javax.swing.JButton bt_color;
    private javax.swing.JButton bt_ingresar;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JComboBox<String> cb_confort;
    private javax.swing.JComboBox<String> cb_dueno;
    private javax.swing.JComboBox<String> cb_mensaje_personas;
    private javax.swing.JComboBox<String> cb_mensajes_recibidos;
    private javax.swing.JComboBox<String> cb_modificar;
    private javax.swing.JComboBox<String> cb_rol;
    private javax.swing.JComboBox<String> cb_tipo_objetos;
    private javax.swing.JComboBox<String> cb_tipo_persona;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox7;
    private com.toedter.components.JLocaleChooser jL_elaborado_pais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_crear_objetos;
    private javax.swing.JButton jb_enviar_mensaje;
    private com.toedter.calendar.JDateChooser jd_fecha;
    private javax.swing.JRadioButton rb_f;
    private javax.swing.JRadioButton rb_m;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField tf_altura;
    private javax.swing.JTextField tf_contra_r;
    private javax.swing.JTextField tf_contrasena;
    private javax.swing.JTextField tf_descripcion;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_estado_civil;
    private javax.swing.JTextField tf_horarios;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_intrucciones;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_material;
    private javax.swing.JTextField tf_mensaje_enviar;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_ocupacion;
    private javax.swing.JTextField tf_peso;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_talla_ropa;
    private javax.swing.JTextField tf_talla_zapatos;
    private javax.swing.JTextField tf_tamano;
    private javax.swing.JTextField tf_tiempo_trabajando;
    private javax.swing.JTextField tf_tiempo_vida;
    private javax.swing.JTextField tf_tipo_suela;
    private javax.swing.JTextField tf_trabajo;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JTextField tf_usuario_r;
    // End of variables declaration//GEN-END:variables
}
